server:
  port: 8772
spring:
  application:
    name: fw-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#ribbon:
#  eureka:
#    enabled: false #禁用eurake
## 禁用 Eureka 后手动配置服务地址
#fw-cloud-ribbon-server: #服务名称
#  ribbon:
#    listOfServers: localhost:8773,localhost:8774
