server:
  port: 8678
spring:
  application:
    name: fw-hystrix-feign-dashboard
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: fw-hystrix-ribbon, fw-hystrix-feign
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  instanceUrlSuffix: actuator/hystrix.stream